### ISSUE TITLE
Flaky functional tests against Fulvous - Investigate & Fix

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#161] opened 2020-02-03 17:44 UTC
Error 1:
```
2020-02-03 18:49:48        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
2020-02-03 18:49:48             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
    at errorHandler (/usr/src/node_modules/@polkadot/rpc-core/index.js:234:26)
    at provider.subscribe.then.catch.error (/usr/src/node_modules/@polkadot/rpc-core/index.js:214:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-02-03 18:49:48        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
(node:27) UnhandledPromiseRejectionWarning: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: BadProof
    at errorHandler (/usr/src/node_modules/@polkadot/rpc-core/index.js:234:26)
    at provider.subscribe.then.catch.error (/usr/src/node_modules/@polkadot/rpc-core/index.js:214:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) should commit anchor and move anchor
```

**Comment by philipstanislaus** [comment] 2020-02-03 17:52
Duplicate of #158 , closing #158.

**Comment by mustermeiszer** [comment] 2022-04-07 07:45
@mikiquantum still relevant? if yes, feel free to re-open.

**Closed by mustermeiszer** 2022-04-07 07:45 UTC
