### ISSUE TITLE
Node isn't syncing for a long time

### ISSUE THREAD

**Issue by ok-everstake** [centrifuge/centrifuge-chain#320] opened 2021-04-09 20:24 UTC
#### Description
The new node isn't syncing/not connecting to peers for a long time on the Mainnet.

#### Steps to reproduce 
Start node from scratch with versions
- Release from documentation - `v2.0.0-rc6.0` 
or then
- Latest - `v2.0.0-rc6-241-1` 

Bootnodes from documentation - https://docs.centrifuge.io/chain/get-started/run-node/
```
--bootnodes=/ip4/34.89.245.58/tcp/30333/p2p/12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr --bootnodes=/ip4/35.246.188.4/tcp/30333/p2p/12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU
```
#### Behavior
The node isn't syncing for a long time.
More than 10 minutes now and during this week more than an hour (just didn't wait any longer).   
```
2021-04-09 21:13:13.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 1.7kiB/s ⬆ 1.4kiB/s
2021-04-09 21:13:18.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.5kiB/s
2021-04-09 21:13:23.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2021-04-09 21:13:28.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:13:33.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0 ⬆ 0
2021-04-09 21:13:38.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:13:43.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2021-04-09 21:13:48.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2021-04-09 21:13:53.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:13:58.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 5 B/s ⬆ 12 B/s
2021-04-09 21:14:03.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:08.342 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:13.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 1.3kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:18.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 74 B/s ⬆ 0.1kiB/s
2021-04-09 21:14:23.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.7kiB/s ⬆ 0.7kiB/s
2021-04-09 21:14:28.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2021-04-09 21:14:33.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:38.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 4 B/s ⬆ 5 B/s
2021-04-09 21:14:43.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:48.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:53.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:14:58.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0 ⬆ 0
2021-04-09 21:15:03.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.8kiB/s ⬆ 0.9kiB/s
2021-04-09 21:15:08.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
2021-04-09 21:15:13.343 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 1.0kiB/s ⬆ 0.9kiB/s
2021-04-09 21:15:18.344 tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5), ⬇ 0.4kiB/s ⬆ 0.4kiB/s
```
#### Expected behavior
The node starts syncing immediately on the Mainnet as a node on the Testnet Amber.

**Comment by vedhavyas** [comment] 2021-04-20 12:38
@ok-everstake is the node still not syncing? I was not able to reproduce the issue. Would be great if you could provide more details of your setup so that we can figure out the underlying issue

**Comment by ok-everstake** [comment] 2021-04-26 10:23
@vedhavyas node is syncing now. 
I was unable to sync the new node during 06.04 - 08.04 days. Could it be related to this issue https://github.com/centrifuge/centrifuge-chain/issues/269 ? Could we start to sync the new node during migration?
Steps: 
Tried versions v2.0.0-rc6.0 - v2.0.0-rc6-241-1 
The node didn't start syncing, had in logs `tokio-runtime-worker INFO substrate  💤 Idle (0 peers), best: #0 (0x67dd…d1b5), finalized #0 (0x67dd…d1b5)`  for a long time

**Comment by vedhavyas** [comment] 2021-04-26 11:01
@ok-everstake If your node's request was not responded to by the peers, then your node will not sync. There could be network issues etc... Did you change anything? If so, is there a way to reproduce this? We are unable to reproduce this on our end

**Comment by ok-everstake** [comment] 2021-04-26 11:23
@vedhavyas No, I haven't changed anything.
"If so, is there a way to reproduce this?" - Start node from scratch. For example, delete mainnet/db folder and start again. The new node isn't syncing/not connecting to peers for a long time for me

**Comment by mikiquantum** [comment] 2021-04-28 01:56
@ok-everstake I recently synced from scratch a few times in the last week. What I think might be happening is that the bootnodes are at capacity and can't accept more peers from time to time. Once routing table knows about more peers it should not be a problem.
If that happens again, could you enable `--log=main,debug` to understand more about the syncing process.

**Comment by ok-everstake** [comment] 2021-04-30 17:54
@mikiquantum thanks, I see the point.
It happens again whenever I try
```
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sub-libp2p  Libp2p => Connection (ConnectionId(TaskId(92)),Dialer { address: "/ip4/35.246.188.4/tcp/30333" }) to 12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU closed.
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sync  Connection ConnectionId(TaskId(92)) with 12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU closed with ongoing sync request: OngoingRequest { emitted: Instant { tv_sec: 2152658, tv_nsec: 216480811 }, request: BlockRequest { id: 0, fields: HEADER | BODY | JUSTIFICATION, from: Number(128), to: None, direction: Descending, max: Some(128) }, timeout: Delay }
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sub-libp2p  Libp2p => Disconnected(12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU): Was enabled.
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sub-libp2p  PSM <= Dropped(12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU)
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sub-libp2p  PSM => Connect(PeerId("12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU")): Will start to connect at until Instant { tv_sec: 2152667, tv_nsec: 279636774 }
2021-04-30 20:05:37.023 tokio-runtime-worker DEBUG sub-libp2p  External API => Disconnect PeerId("12D3KooWCUjDbbhJf1o6skuE1EJ5PnKpJMaK6scmvWsHnjAULzDU")
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG multistream_select::listener_select  Listener: confirming protocol: /ipfs/id/1.0.0
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG multistream_select::listener_select  Listener: sent confirmed protocol: /ipfs/id/1.0.0
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Successfully applied negotiated protocol
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG multistream_select::dialer_select  Dialer: Received confirmation for protocol: /ipfs/id/1.0.0
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Successfully applied negotiated protocol
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG libp2p_identify::protocol  Sending identify info to client
2021-04-30 20:05:37.028 tokio-runtime-worker DEBUG sub-libp2p  PSM <= Discovered(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr"))
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Successfully applied negotiated protocol
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Failed to apply negotiated protocol
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG multistream_select::dialer_select  Dialer: Received confirmation for protocol: /mainnet/sync/2
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Failed to apply negotiated protocol
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_core::upgrade::apply  Failed to apply negotiated protocol
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  Handler(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr")) => Endpoint Dialer { address: "/ip4/34.89.245.58/tcp/30333" } closed for custom protocols: All substreams have been closed by the remote
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  Handler(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr")) <= Disable
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG multistream_select::dialer_select  Dialer: Proposed protocol: /substrate/mainnet/6
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  PSM <= Dropped(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr"))
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  External API <= Closed(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr"))
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  PSM => Connect(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr")): Enabling connections.
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_tcp  Dropped TCP connection to 34.89.245.58:30333
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG sub-libp2p  Handler(PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr")) <= Enable
2021-04-30 20:05:37.029 tokio-runtime-worker DEBUG libp2p_swarm  Connection Connected { endpoint: Dialer { address: "/ip4/34.89.245.58/tcp/30333" }, info: PeerId("12D3KooWAVAMPNJywZS3J4be8gFGZACfgt1rXS3MyJ2MxEGtLXjr") } closed: Handler(Handler(A(A(A(A(A(Legacy(ConnectionKillError))))))))
```

**Comment by mustermeiszer** [comment] 2022-04-07 07:47
@ok-everstake I am closing this, if this is still an issue feel free to re-open.

**Closed by mustermeiszer** 2022-04-07 07:47 UTC
