### ISSUE TITLE
what is the centrifuge endpoint ?

### ISSUE THREAD

**Issue by LXHLeaner** [centrifuge/centrifuge-chain#867] opened 2022-07-16 12:20 UTC
why the  endpoint "wss://fullnode.centrifuge.io" response the date is https://centrifuge-standalone-history.subscan.io/
but not the https://centrifuge.subscan.io/

**Comment by offerijns** [comment] 2022-07-18 08:24
Duplicate of https://github.com/centrifuge/go-substrate-rpc-client/issues/282#issuecomment-1186808024

**Closed by offerijns** 2022-07-18 08:24 UTC
