### ISSUE TITLE
Discussion of adding ORML

### ISSUE THREAD

**Issue by 99Kies** [centrifuge/centrifuge-chain#653] opened 2022-02-25 18:44 UTC
I have added the orml_tokens and orml_xtokens module to my parallel chain. I can use this module to query the balance of relay tokens of the accounts under the parachain, but I cannot find the balance of the native tokens of the parachain. And when I performed `xtokens.Transfer(native_token_A, chainB)` in chainA, the xcm log returned `BalanceTooLow` error.
this my orml config.
```rust
// orml_xtokens
#[derive(Encode, Decode, Eq, PartialEq, Copy, Clone, RuntimeDebug, PartialOrd, Ord, codec::MaxEncodedLen, TypeInfo)]
#[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
pub enum CurrencyId {
	// / Relay chain token.
	ROC,
	// Native TokenSymbol
	A,
	// Parachain B token.
	CAIR,
}

pub type Amount = i128;

pub struct CurrencyIdConvert;
impl Convert<CurrencyId, Option<MultiLocation>> for CurrencyIdConvert {
	fn convert(id: CurrencyId) -> Option<MultiLocation> {
		match id {
			CurrencyId::ROC => Some(Parent.into()),
			CurrencyId::A => Some((Parent, Parachain(1000), GeneralKey("A".into())).into()),
			CurrencyId::CAIR => Some((Parent, Parachain(2000), GeneralKey("CAIR".into())).into()),
		}
	}
}

impl Convert<MultiLocation, Option<CurrencyId>> for CurrencyIdConvert {
	fn convert(l: MultiLocation) -> Option<CurrencyId> {
		let a: Vec<u8> = "A".into();
		let cair: Vec<u8> = "CAIR".into();
		if l == MultiLocation::parent() {
			return Some(CurrencyId::ROC);
		}
		match l {
			MultiLocation { parents, interior } if parents == 1 => match interior {
				X2(Parachain(1000), GeneralKey(k)) if k == a => Some(CurrencyId::A),
				X2(Parachain(2000), GeneralKey(k)) if k == cair => Some(CurrencyId::CAIR),
				_ => None,
			},
			MultiLocation { parents, interior } if parents == 0 => match interior {
				X1(GeneralKey(k)) if k == a => Some(CurrencyId::A),
				X1(GeneralKey(k)) if k == cair => Some(CurrencyId::CAIR),
				_ => None,
			},
			_ => None,
		}
	}
}

impl Convert<MultiAsset, Option<CurrencyId>> for CurrencyIdConvert {
	fn convert(a: MultiAsset) -> Option<CurrencyId> {
		if let MultiAsset {
			fun: Fungible(_),
			id: Concrete(id),
		} = a
		{
			Self::convert(id)
		} else {
			Option::None
		}
	}
}

pub struct AccountIdToMultiLocation;
impl Convert<AccountId, MultiLocation> for AccountIdToMultiLocation {
	fn convert(account: AccountId) -> MultiLocation {
		X1(AccountId32 {
			network: NetworkId::Any,
			id: account.into(),
		})
		.into()
	}
}


parameter_types! {
	pub SelfLocation: MultiLocation = MultiLocation::new(1, X1(Parachain(ParachainInfo::parachain_id().into())));
	pub const BaseXcmWeight: Weight = 100_000_000;
	pub const MaxAssetsForTransfer: usize = 2;
}

impl orml_xtokens::Config for Runtime {
	type Event = Event;
	type Balance = Balance;
	type CurrencyId = CurrencyId;
	type CurrencyIdConvert = CurrencyIdConvert;
	type AccountIdToMultiLocation = AccountIdToMultiLocation;
	type SelfLocation = SelfLocation;
	type XcmExecutor = XcmExecutor<XcmConfig>;
	type Weigher = FixedWeightBounds<UnitWeightCost, Call, MaxInstructions>;
	type BaseXcmWeight = BaseXcmWeight;
	type LocationInverter = LocationInverter<Ancestry>;
	type MaxAssetsForTransfer = MaxAssetsForTransfer;
}

parameter_type_with_key! {
	pub ExistentialDeposits: |currency_id: CurrencyId| -> Balance {
		// every currency has a zero existential deposit
		match currency_id {
			_ => 0,
		}
	};
}

parameter_types! {
	pub ORMLMaxLocks: u32 = 2;
}

impl orml_tokens::Config for Runtime {
	type Event = Event;
	type Balance = Balance;
	type Amount = Amount;
	type CurrencyId = CurrencyId;
	type WeightInfo = ();
	type ExistentialDeposits = ExistentialDeposits;
	type OnDust = ();
	type MaxLocks = ORMLMaxLocks;
	type DustRemovalWhitelist = Nothing;
}
```

**Comment by 99Kies** [comment] 2022-02-25 18:46
I can transfer relay chain tokens. But parallel chain native tokens don't work

**Comment by 99Kies** [comment] 2022-02-25 18:47
I always wonder if my CurrencyId::A and is not bound to Balance.

**Comment by NunoAlexandre** [comment] 2022-02-25 18:49
@99Kies can you show your xcm config or at least the AssetTransactor? I might take a while to get back to you but hang in there 👍

**Comment by 99Kies** [comment] 2022-02-25 18:52
@NunoAlexandre  thanks!
this is my XcmConfig.
```rust
match_type! {
	pub type SpecParachain: impl Contains<MultiLocation> = {
		MultiLocation {parents: 1, interior: X1(Parachain(1000))} |
		MultiLocation {parents: 1, interior: X1(Parachain(2000))}
	};
}

pub type Barrier = (
	TakeWeightCredit,
	AllowTopLevelPaidExecutionFrom<Everything>,
	AllowUnpaidExecutionFrom<ParentOrParentsExecutivePlurality>,
	// ^^^ Parent and its exec plurality get free execution
	AllowUnpaidExecutionFrom<SpecParachain>,
);


pub type LocalAssetTransactor = MultiCurrencyAdapter<
	Tokens,
	(),
	IsNativeConcrete<CurrencyId, CurrencyIdConvert>,
	AccountId,
	LocationToAccountId,
	CurrencyId,
	CurrencyIdConvert,
	(),
>;

/// A trader who believes all tokens are created equal to "weight" of any chain,
/// which is not true, but good enough to mock the fee payment of XCM execution.
///
/// This mock will always trade `n` amount of weight to `n` amount of tokens.
pub struct AllTokensAreCreatedEqualToWeight(MultiLocation);
impl WeightTrader for AllTokensAreCreatedEqualToWeight {
	fn new() -> Self {
		Self(MultiLocation::parent())
	}

	fn buy_weight(&mut self, weight: Weight, payment: Assets) -> Result<Assets, XcmError> {
		let asset_id = payment
			.fungible
			.iter()
			.next()
			.expect("Payment must be something; qed")
			.0;
		let required = MultiAsset {
			id: asset_id.clone(),
			fun: Fungible(weight as u128),
		};

		if let MultiAsset {
			fun: _,
			id: Concrete(ref id),
		} = &required
		{
			self.0 = id.clone();
		}

		let unused = payment.checked_sub(required).map_err(|_| XcmError::TooExpensive)?;
		Ok(unused)
	}

	fn refund_weight(&mut self, weight: Weight) -> Option<MultiAsset> {
		if weight.is_zero() {
			None
		} else {
			Some((self.0.clone(), weight as u128).into())
		}
	}
}

pub struct XcmConfig;
impl Config for XcmConfig {
    type Call = Call;
    type XcmSender = XcmRouter;
    // How to withdraw and deposit an asset.
    type AssetTransactor = LocalAssetTransactor;
    type OriginConverter = XcmOriginToTransactDispatchOrigin;
    type IsReserve = MultiNativeAsset;
    type IsTeleporter = (); // Teleporting is disabled.
    type LocationInverter = LocationInverter<Ancestry>;
    type Barrier = Barrier;
    type Weigher = FixedWeightBounds<UnitWeightCost, Call, MaxInstructions>;
    type Trader = UsingComponents<IdentityFee<Balance>, RelayLocation, AccountId, Balances, ()>;
    type ResponseHandler = PolkadotXcm;
    type AssetTrap = PolkadotXcm;
    type AssetClaims = PolkadotXcm;
    type SubscriptionService = PolkadotXcm;
}
```

**Comment by NunoAlexandre** [comment] 2022-02-25 20:25
@99Kies so, I might be mistaken and overseeing something, but I think the error you are seeing,

> the xcm log returned `BalanceTooLow` error.

is caused by a misconfigured `Trader` in your `XcmConfig`.

Your `Trader` only handles the Relay chain token (see `RelayLocation`) which is why that one works but not your native tokens. You will need to create rules to handle the other tokens.

Have a look at [how we do it](https://github.com/centrifuge/centrifuge-chain/blob/214dafc3763ea178cb1e7d73bec5b47e7b088223/runtime/development/src/lib.rs#L1227-L1253) or [Acala](https://github.com/AcalaNetwork/Acala/blob/969878303c90f9a019df32b017e87c76c6b5d73e/runtime/karura/src/xcm_config.rs#L215-L229). I was facing the same issue when setting up our initial xcm config and setup and following Acala's example fixed it.

Another thing you might need to look into is ensure that the accounts involved (the sender, the receiver, and the sender parachain's account) have enough balance in the appropriate places. But first try and tackle the `Trader` part and go from there, I would say.

I would also advise you to try and setup e2e sets using the `xcm-simulator` / `xcm-emulator`. Again, you can look at our example in `runtime/integration-tests` or likewise in Acala's repo.

Finally, I am happy to help but this is not an appropriate place to pose this general question that is unrelated to this repo.

**Comment by 99Kies** [comment] 2022-02-26 10:48
@NunoAlexandre thanks! I'm trying it now! Thank you for your help!

**Comment by 99Kies** [comment] 2022-02-26 18:37
@NunoAlexandre  I found that all the cases under Trader provided by you use FixedRateOfFungible.  I can understand that this is a configuration to set a fixed interest rate.   If my parallel chain is going to join KSM, how do I leave this "interest rate" to the market?

**Comment by 99Kies** [comment] 2022-02-26 19:05
I tried to match [this configuration](https://github.com/centrifuge/centrifuge-chain/blob/214dafc3763ea178cb1e7d73bec5b47e7b088223/runtime/development/src/lib.rs#L1227-L1253) but still failed.
```rust
/// Trader - The means of purchasing weight credit for XCM execution.
/// We need to ensure we have at least one rule per token we want to handle or else
/// the xcm executor won't know how to charge fees for a transfer of said token.
pub type Trader = (
	FixedRateOfFungible<NativePerSecond, ()>,
	FixedRateOfFungible<CairPerSecond1000, ()>,
	FixedRateOfFungible<CairPerSecond2000, ()>,
);

parameter_types! {
	pub NativePerSecond: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(1000), GeneralKey(CurrencyId::A.encode())),
		).into(),
		//TODO(nuno): we need to fine tune this value later on
		10_000,
	);

	pub CairPerSecond1000: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(1000), GeneralKey(CurrencyId::CAIR.encode())),
		).into(),
		//TODO(nuno): we need to fine tune this value later on
		200_000
	);

	/// We support this Trader for testing purposes when we spawn a sibling clone development
	/// parachain with id 3000.
	pub CAIRPerSecond2000: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(2000), GeneralKey(CurrencyId::CAIR.encode())),
		).into(),
		//TODO(nuno): we need to fine tune this value later on
		200_000
	);
}
```
![image](https://user-images.githubusercontent.com/45918704/155855753-9a2a6d17-a142-465a-9160-c0119e3223ef.png)

**Comment by 99Kies** [comment] 2022-02-26 19:07
So my test environment looks like this, one is parallel chain A,(para id is 1000) one is parallel chain B (para id is 2000).

**Comment by 99Kies** [comment] 2022-02-27 06:45
@NunoAlexandre Could it be because of the AssetTransactor configuration? It involves a lot of things.

**Comment by NunoAlexandre** [comment] 2022-03-03 07:47
Closing this in favour of #666 😈

**Closed by NunoAlexandre** 2022-03-03 07:47 UTC
